name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  debug_job:
    runs-on: ubuntu-latest
    name: Debug Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Debug Information
        run: |
          echo "Debugging information for the pull request"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "VITE_AUTHOR_DATA_FILE_EXTENSION: ${{ vars.VITE_AUTHOR_DATA_FILE_EXTENSION }}"
          echo "VITE_LOCALE_BASE: ${{ vars.VITE_LOCALE_BASE }}"
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_AUTHOR_DATA_BASE: ${{ secrets.VITE_AUTHOR_DATA_BASE }}
          VITE_APPINSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.VITE_APPINSIGHTS_CONNECTION_STRING}}
          VITE_LOCALE_BASE: ${{ secrets.VITE_LOCALE_BASE }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_MOSS_050CAF31E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  finish_job:    
    runs-on: ubuntu-latest
    name: Finish the Job
    steps:
      - name: Finish the job
        id: finishthejob
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_MOSS_050CAF31E }}
          app_location: "/" # App source code path
          action: "close"
